# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42f6dadbeb6e2a6f67e07706b624746e9e67489c98b54934f85460ecb99eb6888fdb9aa87127b699a89d047e62bfd81e1fc7ea02c23b6445c246908bb202528

test:
  secret_key_base: 5f03cf18a25c2e9c53b6382db00852afd6b3243815bf9325c93221d114d5f6c414ca3f2520c7a128357dec9debf4deace4b87d8bb0d4894d310e8b146bb6999d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
